#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_plotbag.plot import Plotbag

plugin = 'rqt_plotbag.plot.Plotbag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plotbag.add_arguments))
