#!/usr/bin/env python

import sys
import os
import subprocess

os.environ['ROS_MASTER_URI'] = 'http://127.0.0.1:22422/'

import rospy

from rqt_gui.main import Main
from rqt_plotbag.plot import Plotbag


try:
    run_id = rospy.get_param('/run_id')
except:
    print("Auto-launching local roscore")
    subprocess.Popen(['roscore','-p','22422'], stderr=open(os.devnull, 'w'), stdout=open(os.devnull, 'w'))

plugin = 'rqt_plotbag.plot.Plotbag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plotbag.add_arguments))
